# Generated by Django 4.0.4 on 2022-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancerMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_mean', models.FloatField()),
                ('area_mean', models.FloatField()),
                ('concavity_mean', models.FloatField()),
                ('area_se', models.FloatField()),
                ('concavity_se', models.FloatField()),
                ('fractal_dimension_se', models.FloatField()),
                ('smoothness_worst', models.FloatField()),
                ('concavity_worst', models.FloatField()),
                ('symmetry_worst', models.FloatField()),
                ('fractal_dimension_worst', models.FloatField()),
            ],
        ),
    ]
